# Generated by Django 4.2.11 on 2024-03-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_users_groups_users_is_staff_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
    ]
